const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const menu = fs.readFileSync(path.join(__dirname, "..", "XComposeMenu.qml"), "utf8")
assert.match(menu, /event\.key === Qt\.Key_C && \(event\.modifiers & Qt\.ControlModifier\).*copyResult/)
assert.doesNotMatch(menu, /Qt\.Key_Return \|\| event\.key === Qt\.Key_Enter\).*ControlModifier/)
assert.match(menu, /event\.key === Qt\.Key_F && \(event\.modifiers & Qt\.ControlModifier\).*toggleFavorite/)
assert.match(menu, /event\.key === Qt\.Key_P && \(event\.modifiers & Qt\.ControlModifier\).*togglePreview/)
assert.match(menu, /function filterDisplayText\(\)[\s\S]*replace\(\/ \/g, "▁"\)/)
assert.match(menu, /function setFilter\(value\).*rebuildDisplay\(true\)/)
assert.doesNotMatch(menu, /onContainsMouseChanged/)
assert.doesNotMatch(menu, /id: quickActions/)
assert.match(menu, /id: footer[\s\S]*id: footerActions[\s\S]*id: footerStatus/)
assert.match(menu, /property var selectedBorderSpec: Border\.surfaceSpec\("menu", "selected-border"/)
assert.match(menu, /id: searchIcon[\s\S]*text: "󰍉"/)
assert.doesNotMatch(menu, /id: resultIconCell/)
assert.match(menu, /Enter insert.*Ctrl\+C copy.*Ctrl\+P preview.*Esc close/)
assert.match(menu, /↑\/↓ navigate.*Ctrl\+F favorite.*Tab variants/)
assert.match(menu, /id: favoriteCell[\s\S]*text: "󰓎"/)
assert.match(menu, /anchors\.left: favoriteCell\.right/)
assert.match(menu, /font\.pixelSize: preview\.length <= 3 \? Style\.font\.iconLarge : Style\.font\.title/)
assert.doesNotMatch(menu, /id: selectionCell/)
assert.match(menu, /readonly property bool hasCursor: index === root\.selectedIndex/)
assert.match(menu, /borderSpec: hasCursor \? root\.selectedBorderSpec : Border\.none\(\)/)
assert.match(menu, /<b><u>/)
assert.match(menu, /previewMarkup/)
assert.match(menu, /sequenceMarkup/)
assert.match(menu, /id: previewPane/)
assert.match(menu, /id: previewScroll[\s\S]*contentHeight: Math\.max\(height, fullPreviewText\.implicitHeight\)/)
assert.match(menu, /id: fullPreviewText[\s\S]*text: root\.previewResult[\s\S]*textFormat: Text\.PlainText[\s\S]*wrapMode: Text\.WrapAnywhere/)
assert.doesNotMatch(menu, /onLoaded:.*text\(\)/)
assert.match(menu, /id: composeFile[\s\S]*blockAllReads: true[\s\S]*preload: false[\s\S]*onFileChanged: root\.readCompose\(\)/)
assert.match(menu, /id: favoritesFile[\s\S]*blockAllReads: true[\s\S]*preload: false[\s\S]*onFileChanged: root\.readFavorites\(\)/)
assert.match(menu, /id: historyFile[\s\S]*blockAllReads: true[\s\S]*preload: false[\s\S]*onFileChanged: root\.readHistory\(\)/)
assert.match(menu, /function startBoundedRead\(process, path, limit\)[\s\S]*scripts\/read-bounded\.js/)
assert.match(menu, /scripts\/read-compose-tree\.js/)
assert.match(menu, /XComposeParser\.combine\(/)
assert.match(menu, /id: includeWatchers[\s\S]*model: root\.composeSources/)
console.log("menu shortcut tests passed")
