const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const menu = fs.readFileSync(path.join(__dirname, "..", "XComposeMenu.qml"), "utf8")
assert.match(menu, /event\.key === Qt\.Key_C && \(event\.modifiers & Qt\.ControlModifier\).*copyResult/)
assert.doesNotMatch(menu, /Qt\.Key_Return \|\| event\.key === Qt\.Key_Enter\).*ControlModifier/)
assert.match(menu, /event\.key === Qt\.Key_F && \(event\.modifiers & Qt\.ControlModifier\).*toggleFavorite/)
assert.match(menu, /event\.key === Qt\.Key_P && \(event\.modifiers & Qt\.ControlModifier\).*togglePreview/)
assert.match(menu, /function filterDisplayText\(\)[\s\S]*replace\(\/ \/g, "▁"\)/)
assert.match(menu, /function setFilter\(value\).*rebuildDisplay\(true\)/)
assert.doesNotMatch(menu, /onContainsMouseChanged/)
assert.doesNotMatch(menu, /id: quickActions/)
assert.match(menu, /id: footer[\s\S]*id: footerActions[\s\S]*id: footerStatus/)
assert.match(menu, /property var selectedBorderSpec: Border\.surfaceSpec\("menu", "selected-border"/)
assert.match(menu, /id: searchIcon[\s\S]*text: "󰍉"/)
assert.match(menu, /id: sourceBadge[\s\S]*text: root\.sourceName\(\)/)
assert.doesNotMatch(menu, /id: resultIconCell/)
assert.match(menu, /Enter insert.*Ctrl\+C copy.*Ctrl\+P preview.*Esc close/)
assert.match(menu, /↑\/↓ navigate.*Ctrl\+F favorite.*Tab variants/)
assert.match(menu, /id: favoriteCell[\s\S]*text: "󰓎"/)
assert.match(menu, /anchors\.left: favoriteCell\.right/)
assert.match(menu, /font\.pixelSize: preview\.length <= 3 \? Style\.font\.iconLarge : Style\.font\.title/)
assert.doesNotMatch(menu, /id: selectionCell/)
assert.match(menu, /readonly property bool hasCursor: index === root\.selectedIndex/)
assert.match(menu, /borderSpec: hasCursor \? root\.selectedBorderSpec : Border\.none\(\)/)
assert.match(menu, /previewMarkup/)
assert.match(menu, /sequenceMarkup/)
assert.match(menu, /import "XComposeViewModel\.js" as XComposeViewModel/)
assert.match(menu, /function toggleDiagnostics\(\)/)
assert.match(menu, /event\.key === Qt\.Key_D && \(event\.modifiers & Qt\.ControlModifier\).*toggleDiagnostics/)
assert.match(menu, /id: diagnosticsPane[\s\S]*text: root\.diagnosticsContent\(\)/)
const viewModel = fs.readFileSync(path.join(__dirname, "..", "XComposeViewModel.js"), "utf8")
assert.match(viewModel, /"<b><u>"/)
assert.match(viewModel, /function highlightMarkup\(value, ranges\)/)
assert.match(viewModel, /sensitiveMask = "󰌾 ••••••"/)
assert.match(viewModel, /function buildRow\(group, variant, variantIndex, match, options\)/)
assert.match(viewModel, /function previewResultText\(variant, result, options\)/)
assert.match(menu, /id: previewPane/)
assert.match(menu, /id: previewScroll[\s\S]*contentHeight: Math\.max\(height, fullPreviewText\.implicitHeight\)/)
assert.match(menu, /id: fullPreviewText[\s\S]*text: root\.previewResult[\s\S]*textFormat: Text\.PlainText[\s\S]*wrapMode: Text\.WrapAnywhere/)
assert.doesNotMatch(menu, /onLoaded:.*text\(\)/)
assert.match(menu, /id: composeFile[\s\S]*blockAllReads: true[\s\S]*preload: false[\s\S]*onFileChanged: root\.readCompose\(\)/)
assert.match(menu, /id: favoritesFile[\s\S]*blockAllReads: true[\s\S]*preload: false[\s\S]*onFileChanged: root\.readFavorites\(\)/)
assert.match(menu, /id: historyFile[\s\S]*blockAllReads: true[\s\S]*preload: false[\s\S]*onFileChanged: root\.readHistory\(\)/)
assert.doesNotMatch(menu, /id: composeRead[\s\S]*StdioCollector/)
assert.match(menu, /id: composeRead[\s\S]*scriptPath: root\.pluginDir \+ "\/scripts\/read-compose\.js"[\s\S]*onLoaded: function\(text\) \{ root\.loadCompose\(text\) \}/)
assert.match(menu, /function readCompose\(\) \{[\s\S]*composeRead\.read\(composePath, maxComposeBytes, \[JSON\.stringify\(readOptions\(\)\)\]\)/)
assert.match(menu, /function readOptions\(\)[\s\S]*includes: \{ enabled: config\.includes\.enabled, roots: includeRoots\(\) \}/)
assert.match(menu, /restrictRoot: composeSourceOrigin === "payload"/)
assert.match(menu, /allowExternalPaths: config\.security\.allowExternalPaths/)
assert.match(menu, /function allowedRoots\(\)[\s\S]*config\.security\.allowedRoots\.forEach/)
assert.match(menu, /selection\.origin === "payload" && !config\.security\.allowExternalPaths && !XComposeConfig\.pathAllowed/)
assert.match(menu, /id: secretFile[\s\S]*onSaved: root\.launchPendingFromFile\(\)/)
assert.match(menu, /onSaveFailed: function\(error\) \{ root\.secretWriteFailed\(error\) \}/)
assert.match(menu, /function launchPendingFromFile\(\)[\s\S]*"--file", secretPath/)
assert.match(menu, /function secretWriteFailed\(error\)[\s\S]*\["rm", "-f", secretPath\]/)
assert.doesNotMatch(menu, /command\.push\(pendingSecret\)/)
assert.match(menu, /pendingSecret = variant\.result/)
assert.match(menu, /secretWritePending = true/)
assert.match(menu, /"--", variant\.result/)
assert.match(menu, /mkdir", "-p", "-m", "700", secretDir/)
assert.match(menu, /XComposeParser\.parseBundle\(bundle\)/)
assert.match(menu, /function includeRoots\(\)[\s\S]*XComposeConfig\.resolvePath\(root, home\)/)
assert.match(menu, /id: favoritesRead[\s\S]*root\.loadFavorites/)
assert.match(menu, /id: historyRead[\s\S]*root\.loadHistory/)
assert.match(menu, /readonly property int maxComposeBytes: XComposeParser\.maxSourceBytes/)
assert.match(menu, /readonly property int maxStateBytes: XComposeHistory\.maxStateBytes/)

assert.match(menu, /variantIndex === group\.activeVariantIndex[\s\S]*group\.descriptionRanges/)
assert.match(menu, /event\.key === Qt\.Key_R && \(event\.modifiers & Qt\.ControlModifier\).*toggleReveal/)
assert.match(menu, /property string revealedSensitiveId: ""/)
assert.match(menu, /revealSensitive: selected === true && variant && variant\.id === revealedSensitiveId/)
assert.match(menu, /if \(revealedSensitiveId\) \{ revealedSensitiveId = ""; rebuildDisplay\(\); return \}/)
assert.match(menu, /XComposeViewModel\.buildRow\(group, selected\.variant, selected\.variantIndex, match, viewOptions\(selected\.variant, i === selectedIndex\)\)/)
assert.match(menu, /id: previewTagsLine[\s\S]*root\.previewTags/)
assert.match(menu, /text: root\.previewResultText\(\)/)
assert.match(menu, /function previewMetadataText\(\)/)
assert.match(viewModel, /groupId: group\.groupId[\s\S]*description: variant\.descriptionPreview/)
assert.match(viewModel, /function metadataText\(variant\)/)
const reader = fs.readFileSync(path.join(__dirname, "..", "BoundedFileReader.qml"), "utf8")
assert.match(reader, /function read\(targetPath, targetLimit, args\)/)
assert.match(reader, /reader\.pending = true/)
assert.match(reader, /process\.command = \["node", reader\.scriptPath, resolvedPath, String\(resolvedLimit\)\]\.concat\(resolvedArgs \|\| \[\]\)/)
assert.match(reader, /reader\.nextArgs = resolvedArgs/)
assert.match(reader, /signal loaded\(string text\)/)
assert.match(reader, /signal failed\(int exitCode\)/)
console.log("menu shortcut tests passed")
