const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const workflowPath = path.join(__dirname, "..", ".github", "workflows", "tag-release.yml")
const workflow = fs.readFileSync(workflowPath, "utf8")
const ciWorkflow = fs.readFileSync(path.join(__dirname, "..", ".github", "workflows", "ci.yml"), "utf8")

assert.match(ciWorkflow, /push:\s*\n\s*branches:\s*\n\s*- main/)
assert.match(ciWorkflow, /pull_request:\s*\n\s*branches:\s*\n\s*- main/)

assert.match(workflow, /workflow_run:/)
assert.match(workflow, /workflows:\s*\n\s*- CI/)
assert.match(workflow, /branches:\s*\n\s*- main/)
assert.match(workflow, /types:\s*\n\s*- completed/)
assert.match(workflow, /permissions:\s*\n\s*contents: write/)
assert.match(workflow, /if: github\.event\.workflow_run\.conclusion == 'success' && github\.event\.workflow_run\.event == 'push'/)
assert.match(workflow, /uses: actions\/checkout@[0-9a-f]{40}/)
assert.match(workflow, /ref: \$\{\{ github\.event\.workflow_run\.head_sha \}\}/)
assert.doesNotMatch(workflow, /pull_request_target|pull_request\.merged|merge_commit_sha/)
assert.match(workflow, /git diff --quiet "\$TARGET_SHA\^" "\$TARGET_SHA" -- manifest\.json/)
assert.equal((workflow.match(/if: steps\.release\.outputs\.changed == 'true'/g) || []).length, 2)
assert.match(workflow, /JSON\.parse\(fs\.readFileSync\("manifest\.json"/)
assert.match(workflow, /tag=v\$\{version\}/)
assert.match(workflow, /git tag -a "\$TAG"/)
assert.match(workflow, /git push origin "refs\/tags\/\$TAG"/)
assert.match(workflow, /existing_commit="\$\(remote_tag_commit\)"/)
assert.match(workflow, /existing_commit" == "\$TARGET_SHA/)
assert.match(workflow, /remote_tag_commit\)" == "\$TARGET_SHA/)

console.log("workflow tests passed")
